version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_martos
    expose:
      - 80
      - 8080
    ports:
      - 80:80
      - 8080:8080
    environment:
      SWAGGER_JSON: /foo/swagger.json
    volumes:
      - ./swagger:/foo
